// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkvMooBF-eR-nK9Jp4LE3RAN9KrJLsdvg',
    appId: '1:115712534199:web:bce201ff37a50c65c7cf32',
    messagingSenderId: '115712534199',
    projectId: 'gradventure-6e9a2',
    authDomain: 'gradventure-6e9a2.firebaseapp.com',
    storageBucket: 'gradventure-6e9a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_HJmmu9n8Q8Qpp8zUZtnBVAc8f4EAuyQ',
    appId: '1:115712534199:android:b9dff284e5f7f3e4c7cf32',
    messagingSenderId: '115712534199',
    projectId: 'gradventure-6e9a2',
    storageBucket: 'gradventure-6e9a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF0kqhhqUGrRovxJdJqO2GyjgjCSoF4F8',
    appId: '1:115712534199:ios:e67d24b4628f8b7ac7cf32',
    messagingSenderId: '115712534199',
    projectId: 'gradventure-6e9a2',
    storageBucket: 'gradventure-6e9a2.firebasestorage.app',
    iosBundleId: 'com.example.gradventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF0kqhhqUGrRovxJdJqO2GyjgjCSoF4F8',
    appId: '1:115712534199:ios:e67d24b4628f8b7ac7cf32',
    messagingSenderId: '115712534199',
    projectId: 'gradventure-6e9a2',
    storageBucket: 'gradventure-6e9a2.firebasestorage.app',
    iosBundleId: 'com.example.gradventure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkvMooBF-eR-nK9Jp4LE3RAN9KrJLsdvg',
    appId: '1:115712534199:web:1313ee1ed09c8b52c7cf32',
    messagingSenderId: '115712534199',
    projectId: 'gradventure-6e9a2',
    authDomain: 'gradventure-6e9a2.firebaseapp.com',
    storageBucket: 'gradventure-6e9a2.firebasestorage.app',
  );
}
